input UserInput {
  name: String!
  lastname: String!
  email: String!
  password: String!
  referral_code: String
}

input OrderInput {
  address: String!
  phone: String!
}

input ProductInput {
  code: String!
  name: String!
  description: String!
  price: Float!
  image: String
  quantity: Int
  categoryId: Int!
}

type GeneratedOrder {
  message: String
}

type Mutation {
  signUp(user: UserInput!): User!
  signIn(email: String!, password: String!): LoginPayload!
  addProductToCart(productId: Int!): CartItem!
  deleteOneProductFromCart(cartItemId: Int!, productId: Int!): CartItem!
  deleteProductFromCart(cartItemId: Int!, productId: Int!): CartItem!
  deleteCart(cartId: Int!): Cart!
  createOrder(order: OrderInput): GeneratedOrder!
  createProduct(product: ProductInput!): Product!
  updateProduct(productId: Int!, product: ProductInput!): Product!
  deleteProduct(id: Int!): Product!
  addCategory(name: String!, icon: String): Category!
  editCategory(id: Int!, name: String!, icon: String): Category!
  deleteCategory(id: Int!): Category!
}
