input UserInput {
  name: String!
  lastname: String!
  email: String!
  password: String!
}

type Mutation {
  signUp(user: UserInput!): User!
  signIn(email: String!, password: String!): LoginPayload!
  addProductToCart(productId: Int!): CartItem!
}
